version: '3'
services:
  handler:
    image: handler:latest
    ports:
      - "8080:8080"
    environment:
      - BROKER_HOST=rabbit
      - BROKER_PORT=5672
      - BROKER_USER=guest
      - BROKER_PASS=guest
  rabbit:
    image: rabbitmq:3