{{ if .Values.manifests.handler }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "handler.fullname" . }}
  labels:
    app: {{ template "handler.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.handler.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "handler.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.handler.image.repository }}:{{ .Values.handler.image.tag }}"
          imagePullPolicy: {{ .Values.handler.image.pullPolicy }}
          env:
          - name: BROKER_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-backend-secret"
                key: BROKER_USER
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-backend-secret"
                key: BROKER_PASS
          - name: STORAGE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-backend-secret"
                key: STORAGE_ACCOUNT_NAME
          - name: STORAGE_ACCOUNT_SAS
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-backend-secret"
                key: STORAGE_ACCOUNT_SAS
{{- range $key, $val := .Values.handler.env.service }}
          - name: {{ $key }}
            value: {{ $val | quote }}
{{- end }}
          ports:
            - containerPort: {{ .Values.service.http.externalPort }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.service.http.internalPort }}
            failureThreshold: 5
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.service.http.internalPort }}
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          resources:
{{ toYaml .Values.handler.resources | indent 12 }}
{{ end }}
