{{ if .Values.manifests.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "api.fullname" . }}
              servicePort: 80
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: "tls-{{ template "api.fullname" . }}"
{{ end }}