{{ if .Values.manifests.tls_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "tls-{{ template "api.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
{{ end }}
