{{ if .Values.manifests.handler_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: handler-secret
type: Opaque
data:
{{- range $key, $val := .Values.handler.env.auth }}
    {{ $key }}: {{ $val | b64enc }}
{{- end -}}
{{ end }}
