{{ if .Values.manifests.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "genericwebapp.fullname" . }} #Name of the directory under Chart
  labels:
    app: {{ template "genericwebapp.name" . }} #Name of the directory under Chart
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "genericwebapp.fullname" . }} #Name of the directory under Chart
              servicePort: {{ .Values.service.externalPort }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: "tls-{{ template "genericwebapp.fullname" . }}" #Name of the directory under Chart
{{ end }}